services:
  db:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: plastic
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    secrets:
      - db_root_password

  poodac_downloader:
    build: ./poodac_downloader
    volumes:
      - ./tmp:/app/tmp
      - ./logs:/app/logs
    depends_on:
      file_extractor:
        condition: service_started

  file_extractor:
    build: ./file_extractor
    volumes:
      - ./tmp:/app/tmp
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_started

  forecast_service:
    build:
      context: ./forecast_service
      args:
        - DOCKER_BUILDKIT=1
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_started

  api_endpoint:
    build: ./api_endpoint
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_started

secrets:
  db_root_password:
    file: ./.secrets/db_root_password.txt
